### ISSUE TITLE
[General checks] Contribution and Authorship

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#5]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

> Does the full list of paper authors seem appropriate and complete?

Of course, there is no confusion regarding the authorship of B. Ye and P. Walker. However, there are some contradicting lists of authors. The metadata on pyproject.toml lists as authors B. Ye, P. Walker and A. Glisman, which is different from the list of the paper. Please clarify this and make sure all lists of authors are harmonized.

**Comment by pw0908** [comment]
The short answer here is that, originally, we were going to implement an analysis suit that Alec had implemented. He graduated a few weeks ago and we didn't have the time to port it over. However, his discussions were very helpful in the design of this package and beta testing so we felt it fair to include him on the pyproject.toml. However, since he won't be a maintainer of MDCraft, we didn't feel it was appropriate to include him on the paper.

We would feel more comfortable keeping the authorships as they stand. The only alternative would be to remove Alec from the pyproject.toml. Let us know what you think with this context in mind.

**Comment by pw0908** [comment]
You will also see we acknowledged Alec within the paper.

**Comment by aazocar** [comment]
In my opinion, it would be better to _not_ have an additional author listed on the pyproject.toml who is not on the paper, in order to have a consistent and clear list of authors. 

Another option would be to add A. Glisman to a short Acknowledgment / Contributors section in the readme.

Maybe @srmnitc can weigh in on this?

**Comment by srmnitc** [comment]
I think it is better to be consistent between the different places where the authors are listed. 

@pw0908 Just for clarification from my side. _'However, since he won't be a maintainer of MDCraft, we didn't feel it was appropriate to include him on the paper.'_ The JOSS author guidelines do not need someone to be maintainer on the project. The [authorship guidelines](https://joss.readthedocs.io/en/latest/submitting.html#authorship) also mention 'active project direction and other forms of non-code contributions' as a possible criteria for authorship. That being said, it is up to the authors to decide on the authorships. If A. Glisman is indeed not an author of the paper, please keep it consistent in the repo, and maybe acknowledge them elsewhere as @aazocar points out.

**Comment by pw0908** [comment]
One observation I will briefly make is that it isn't uncommon for the authors on the JOSS paper not to match the authors on the pyproject.toml. Here are a few examples where the JOSS authorship doesn't match the repository authorship:
[stimupy](https://github.com/computational-psychology/stimupy)
[atlite](https://github.com/PyPSA/atlite)
[pycm](https://github.com/sepandhaghighi/pycm)
[Gridap.jl](https://github.com/gridap/Gridap.jl)

These are the cases where there were more authors in the .toml file than the JOSS paper. More often than not, the inverse is usually true, with most cases only having the first author on the .toml, even if the latter authors contributed to the code. I suppose this behaviour is to be expected as open-source projects are inherently collaborative and who counts as an author can change even after the JOSS is published.

All this to say that there is precedent in JOSS for this to occur and that we would much prefer keeping the authorship as it stands. That being said, if this isn't enough to convince you, we'll just remove A. Glisman from our toml.

**Comment by srmnitc** [comment]
@pw0908 Thanks for bringing this to attention. In the list you provided, pycm and gridap.jl have matching list of authors for the version of the code reviewed in JOSS. atlite has a list of authors and contributors. That being said, I am sure you would be able to find more cases where there are differences.

There are four different places where authors are listed:

- pyproject.toml: B. Ye, P. Walker, A. Glisman
- commit history: B. Ye, P. Walker 
- copyright statement in docs: B. Ye, P. Walker, A. Glisman
- paper: B. Ye, P. Walker, Z-G Wang

From this, there are two main things you could clarify that would shed some light on the question "Does the full list of paper authors seem appropriate and complete?"

1. Is A. Glisman an author of the paper? As I mentioned, one does not need to be a maintainer of the code to be a JOSS author. Since you mentioned they were involved in the design of the package, and they are listed on pyproject.toml and copyright statement, could you please confirm that A. Glisman indeed need not be an author of the paper?

2. Open-source projects are inherently collaborative, true, but A. Glisman does not have any commits in this repo. Keeping this in mind, my strong recommendation still is to harmonise the metadata and prevent four conflicting list of authors. I agree this is not a point that directly appears in the JOSS checklist, so the final decision would be up to you.

Thanks for the timely resolution of the review issues!

**Comment by pw0908** [comment]
Answering your questions:
1. A. Glisman was a beta tester of MDCraft (back when it was called MDHelper) and wasn't actually part of the design process. There was a chunk of code they wrote which was always intended to merge in formally but never got around to. As such, because they had been part of the MDCraft journey since the start and we had always intended to include a contribution from them, we felt a good compromise was acknowledging them in the pyproject.toml. That being said, @bbye98  I don't think Alec should be in the License? If anything, Z-G should be.
2. Fair point about harmonising the four different files... @bbye98 that does seem cleaner?

**Comment by srmnitc** [comment]
@pw0908 Thanks for addressing this issue.  All the records are now consistent, @aazocar do you feel the issue is addressed, and we can close this?

**Comment by aazocar** [comment]
> @pw0908 Thanks for addressing this issue. All the records are now consistent, @aazocar do you feel the issue is addressed, and we can close this?

Yes, from my side the issue has been clarified. I will close.
