### ISSUE TITLE
[Functionality/Example usage] Algorithm and analysis modules

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#8]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

`algorithm` and `analysis` modules would also greatly benefit from example use cases. 

Also, from the paper, most of the mentioned features correspond to the `analysis` module, it is not clear from the text what is covered in the `algorithm` module.

**Comment by pw0908** [comment]
For each of these:
1. `analysis`: We definitely should and will include examples for each of these. We'll probably include them within the API docs rather than standalone examples as these tools themselves are not inherently complicated.
2. `algorithm`: This module is intended to be more low-level compared to `analysis` as it provides functions used within the latter module. I will certainly clarify this distinction in the text. I am less certain how helpful examples will be here as, ideally, only advanced users should be looking at these functions and they are sufficiently commented to be easy to follow. Let us know what you think.

**Comment by aazocar** [comment]
1. Including examples in the API docs addressed this point.
2. For `algorithm` module, I agree the examples here are not needed. The comment was intended to clarify the differences between both modules and highlighting the distinction within the text should be enough to close this issue.

**Comment by aazocar** [comment]
looks good to me 👍🏽
